routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', 'LibrosController@index');
Route::get('error',function(){
			abort(500);
			});


Auth::routes();

Route::get('/home', 'UsersController@index');

Route::resource('/libros', 'LibrosController'); //debemos crear esta carpeta materials(donde estan las vistas)

Route::resource('/prestamos', 'PrestamosController'); //debemos crear esta carpeta comentarios

Route::resource('/users', 'UsersController');//debemos crear esta carpeta users

Route::get('/reportes/estadistico','ReportesController@index');//con el metodo index
Route::get('pdf',function(){
	$pdf=PDF::loadView('libros');
	return $pdf->stream('libros');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email','cuenta', 'password', 'nombre', 'apellido', 'foto', 'rol'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;

use Illuminate\Http\Request;
use App\User;  //agregado
use Storage;
use Auth;
use Alert;

class UsersController extends Controller
{
    
      use RegistersUsers;

   /*  public function __construct()
    {
        $this->middleware('auth');
    }  //constructor para no dejar entrar sin autenticar al metodo usuarios   guest
*/


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function index()
    {
        $res = User::All()->Where('rol', '<>', 'Administrador'); //equivalente a selec * from materials // agregado
        return view('users.index', compact('res'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Auth.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

     protected function validar(request $request)
    {
        $this->validate($request, ['email' => 'required',
                                   'password' => 'required',
                                   'nombre' => 'required',
                                   'apellido' => 'required',
            ]);
    }

    public function store(Request $request)
    {
         $this->validar($request); //llamando clase para validar

        //cargando archivo al servidor
        $img = $request->file('foto');
        $nombreImg = time().'_'.$img->getClientOriginalName();
        Storage::disk('fotosLibro')->put($nombreImg, file_get_contents($img->getRealPath()));


        $datos = $request->all();
        // to do pendiente cargar archivos
       $datos += ["foto" => $nombreImg];
        //dd($datos);

        if (User::create($datos)) {
            return back()->with('msj','Datos Guardados');
        }else{
            return back()->with('errormsj','Los Datos no se Guardaron');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //buscando un solo registro
        //$res = User::findOrFail($id); // para buscar por id, el de abajo es para email
        $res = User::Where('email', '=', $id)->first();  //first para devolver un solo valor
        return view('users.show', compact('res'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //$res = User::findOrFail($id); // para buscar por id, el de abajo es para email
        $res = User::Where('email', '=', $id)->first();  //first para devolver un solo valor
        return view('users.edit', compact('res'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $passwordSinEncriptar = $request->input('password');        
        $contraEncriptado=bcrypt($passwordSinEncriptar);

        $datos = $request->all();
        $datos['password']=$contraEncriptado;
        $res = User::findOrFail($id);

        $res->update($datos);
        alert()->success('Los Datos Fueron Modificados Exitosamente', 'OK');
        return redirect('users/');
         
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        alert()->success('Los Datos Fueron Eliminados Exitosamente', 'OK');
        return redirect('users/');
    }

}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-title">
      <h2 class="pmd-card-title-text">Editar Usuario</h2>
  </div>
<div class="panel-body">


    <form role="form" method="POST" action="{{ route('users.update', $res->id) }}" enctype="multipart/form-data" class="form-horizontal">
     <input name="_method" type="hidden" value="PUT">
    {{ csrf_field() }}

     

    <div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label  for="nombre">Nombre:</label>
      <input type="text" class="form-control" name="nombre"   value="{{$res->nombre}}">
      @if($errors->has('nombre'))
      <span style="color:red;">{{ $errors->first('nombre')}}</span>
      @endif
</div>

<div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label  for="apellido">Apellido:</label>
      <input type="text" class="form-control" name="apellido"  value="{{$res->apellido}}">
      @if($errors->has('apellido'))
      <span style="color:red;">{{ $errors->first('apellido')}}</span>
      @endif
</div>
<div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label for="">Email:</label>
      <input type="text" class="form-control" name="email" value="{{$res->email}}">
      @if($errors->has('email'))
      <span style="color:red;">{{ $errors->first('email')}}</span>
      @endif
    </div>

  <div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label for="">Cuenta:</label>
      <input type="text" class="form-control" name="cuenta" value="{{$res->cuenta}}" disabled="on">
      @if($errors->has('cuenta'))
      <span style="color:red;">{{ $errors->first('cuenta')}}</span>
      @endif
  </div>

  <div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label for="">Password:</label>
      <input type="text" class="form-control" name="password" value="">
      @if($errors->has('password'))
      <span style="color:red;">{{ $errors->first('password')}}</span>
      @endif
  </div>

<div class="form-group pmd-textfield pmd-textfield-floating-label {{ $errors->has('rol') ? ' has-error' : '' }}">
                          <label for="rol" class="control-label">

                          </label>
                               <select id="rol" class="form-control" name="rol"  required autofocus >
                               
                                @if($res->rol=='Administrador')
                                 <option selected>Administrador</option>
                                 <option>Bibliotecario</option>
                                 <option >Estudiante</option>
                                @endif
                                @if($res->rol=='Estudiante')
                                 <option>Administrador</option>
                                 <option>Bibliotecario</option>
                                 <option selected>Estudiante</option>
                                @endif
                                @if($res->rol=='Bibliotecario')
                                 <option>Administrador</option>
                                 <option selected>Bibliotecario</option>
                                 <option>Estudiante</option>
                                @endif

                               </select>
                               @if ($errors->has('rol'))
                                   <span class="help-block">
                                       <strong>{{ $errors->first('rol') }}</strong>
                                   </span>
                               @endif
                       </div>


<div class="form-group">
    <div class="col-md-6 col-md-offset-4">
        <div class="btn-group">
          <button type="submit" class="btn  btn-primary">Modificar</button>
          <a href="{{ url('users')}}" class="btn btn-success">Volver</a>
        </div>
    </div>
 </div>

</form>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12 col-md-offset-0">
<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-title">
      <h2 class="pmd-card-title-text">Usuarios</h2>
  </div>

	<div class="panel-body">

	<div class="form-group">
      	<a href="{{ url('register') }}" class="btn btn-info btn-sm">Nuevo</a>
    </div>


<div class="pmd-table-card pmd-card pmd-z-depth">
	
	<table id="datatable" class="table pmd-table table-striped table-hover table">
	    <thead>
	        <tr>
	            <th> Nombre </th>
	            <th> Apellido </th>
	            <th> Rol </th>
	            <th> Cuenta</th>
	            <th> Email</th>
	            <th></th>
	            <!--th> password</th-->
	        </tr>
	    </thead>
	    <tbody>
	        @foreach($res as $f)
	        <tr>	            
	            <td>{{ $f->nombre }}</td>
	            <td>{{ $f->apellido }}</td>
	            <td>{{ $f->rol }}</td>
				<td>{{ $f->cuenta }}</td>
				<td>{{ $f->email }}</td>
				<!--td>{{ $f->password }}</td-->
	            <td>
	            	<a class="btn btn-success btn-sm" href="{{ url('users/'. $f->email) }}"><span class="glyphicon glyphicon-eye-open"></span></a>
	            	<a class="btn btn-info btn-sm" href="{{ url('/users/'. $f->email. '/edit') }}"><span class="glyphicon glyphicon-edit"></span></a>

	            	<!--form action="{{ route('users.destroy', $f->id) }}" method="post" onclick="return confirm('Seguro que quiere eliminar el registro?')" style="display: inline">

	            		<input type="hidden" name="_method" value="DELETE">
	            		{{ csrf_field() }}
	            		<button type="submit" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span></button>
	            	</form-->
	            	<!--Boton de confirmacion MODAL para Eliminar -->
				<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteComment{{$f->id}}">
                  <span class="glyphicon glyphicon-trash"></span>
                </button>
                <!-- Ventana modal para eliminar -->
                <div class="modal fade" id="deleteComment{{$f->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                        <h3 class="pmd-card-title-text">Desea Eliminar este Registro</h3>
                      </div>
                      <div class="modal-body">
                       Usuario : {{$f->cuenta}} 
                       					
                      </div>
                      <div class="modal-footer">
                       		<form action="{{ route('users.destroy', $f->id) }}" method="post" >
								   <input type="hidden" name="_method" value="DELETE">
								   {{ csrf_field() }}
								   <button type="submit" class="btn btn-warning ">Eliminar</button>
								   <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
				         	</form>						
                       
                      </div>
                    </div>
                  </div>
                </div>
                <!--Boton de confirmacion MODAL para Eliminar -->	

	            </td>
	        </tr>
	        @endforeach
	     </tbody>
	    </table>

	    
	</div>


	

	</div>

</div>
</div>
</div>
</div>



@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-title">
      <h2 class="pmd-card-title-text">Usuario</h2>
			 <a href="{{ url('users/')}}" class="btn btn-success"><span class="glyphicon glyphicon-menu-left"></span> Volver</a>
  </div>

<div class="panel-body">
<div class="row">
	<div class="col-xs-12 col-md-4" style="text-align: center">
			<img src="{{ '/imgFotos/'. $res->foto }}" class="img img-rounded img-thumbnail" style="max-width: 180px; max-height: 180px;">

            <a href="{{ url('users/'.$res->email.'/edit') }}">Editar Perfil</a>

            <p></p>
	</div>
	<div class="col-xs-12 col-md-8">
        <table class="table table-borderless">
            <tbody>
                <tr>
                	<th> Nombre </th><td> {{ $res->nombre }} </td>
                </tr>
                <tr>
                	<th> apellido </th><td> {{ $res->apellido }} </td></tr>
                <tr>
                	<th> email </th><td> {{ $res->email }} </td>
            	</tr>
            	<tr>
                	<th> rol </th><td> {{ $res->rol }} </td>
            	</tr>
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
@endsection