routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', 'LibrosController@index');
Route::get('error',function(){
			abort(500);
			});


Auth::routes();

Route::get('/home', 'UsersController@index');

Route::resource('/libros', 'LibrosController'); //debemos crear esta carpeta materials(donde estan las vistas)

Route::resource('/prestamos', 'PrestamosController'); //debemos crear esta carpeta comentarios

Route::resource('/users', 'UsersController');//debemos crear esta carpeta users

Route::get('/reportes/estadistico','ReportesController@index');//con el metodo index
Route::get('pdf',function(){
	$pdf=PDF::loadView('libros');
	return $pdf->stream('libros');
});

app/Libro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
    protected $table = 'libro';

    protected $fillable = ['descripcion', 'cantidad', 'existencia','foto'];
}

app/Http/Controllers/LibrosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Libro;  //agregado
use App\Comentario; //agregado
use Storage;
use Auth;
use Alert;
class LibrosController extends Controller
{

/*
    public function __construct()
    {
        $this->middleware('auth');
    }  //constructor para no dejar entrar sin autenticar al metodo usuarios   //guest
*/
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function index()
    {

        $res = Libro::All(); //equivalente a selec * from materials // agregado
       
        return view('libros.index', compact('res'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('libros.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     protected function validar(request $request)
    {
        $this->validate($request, ['descripcion' => 'required',
                                   'cantidad' => 'required|numeric',
                                   'existencia' => 'required|numeric',
                                   'fotoImg' => 'required',
            ]);
    }
    public function store(Request $request)
    {
        $this->validar($request); //llamando clase para validar

        //cargando archivo al servidor
        $img = $request->file('fotoImg');
        $nombreImg = time().'_'.$img->getClientOriginalName();
        Storage::disk('fotosLibro')->put($nombreImg, file_get_contents($img->getRealPath()));


        $datos = $request->all();
        // to do pendiente cargar archivos
       $datos += ["foto" => $nombreImg];

        //dd($datos);

        if (Libro::create($datos)) {
            
          alert()->success('Datos Guardados Exitosamente', 'OK');
           return back();
            //return back()->with('errors','Datos Guardados');
            //return back()->with('msj','Datos Guardados');

            
        }else{
            alert()->error('Los Datos no se Guardaron', 'Error');
        }
        //return redirect('libros/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //buscando un solo registro
        $res = Libro::findOrFail($id);
       return view('libros.show', compact('res'));
     }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

       $res  = Libro::findOrFail($id);
        return view('libros.edit', compact('res'));
        /* $res=Libro::find($id);
       return view('libros.edit')->with(['edit'=>true, 'res'=>$res]);*/
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validar($request);

         $datos = $request->all();
        $res = Libro::findOrFail($id);

        if(isset($datos['fotoImg']))
        {
        $img = $request->file('fotoImg');
        $nombreImg = time().'_'.$img->getClientOriginalName();
        Storage::disk('fotosLibro')->put($nombreImg, file_get_contents($img->getRealPath()));

            $datos['foto'] = $nombreImg;
        }
        else
        {
            $datos['foto'] =$res->portada;
        }



        //return redirect('libros/');
       if ( $res->update($datos)) {
         alert()->success('Los Datos Fueron Modificados Exitosamente', 'OK');
         return back();
        }else{
            alert()->success('Error', 'Error');
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Libro::destroy($id);
        alert()->success('Dato Eliminado Exitosamente', 'OK');
        //alert('<a href="#">Click me</a>')->html()->persistent("No, thanks");
        return redirect('libros/');
    }
}

resources/views/libros/create.blade.php
@extends('layouts.app')

@section('content')


@if(session()->has('msj'))
<div class="alert alert-success" roler="alert">{{ session('msj') }}</div>
@endif
@if(session()->has('errormsj'))
<div class="alert alert-danger" roler="alert">Error al guardar los datos</div>
@endif


<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-title">
      <h2 class="pmd-card-title-text">Nuevo Libro</h2>
  </div>
<div class="panel-body">
<form role="form" method="POST" action="{{ url('libros')}}" enctype="multipart/form-data" class="form-horizontal">
    {{ csrf_field() }}

<div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label for="descripcion">Descripcion:</label>
      <input type="text" class="mat-input form-control" name="descripcion" >
      @if($errors->has('descripcion'))
      <span style="color:red;">{{ $errors->first('descripcion')}}</span>
      @endif

</div>



<div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label  for="cantidad">Cantidad:</label>
      <input type="text" class="form-control" name="cantidad" >
      @if($errors->has('cantidad'))
      <span style="color:red;">{{ $errors->first('cantidad')}}</span>
      @endif
</div>

<div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label  for="existencia" >Existencia:</label>
      <input type="text" class="form-control" name="existencia"  >
      @if($errors->has('existencia'))
      <span style="color:red;">{{ $errors->first('existencia')}}</span>
      @endif
</div>

<div class="form-group pmd-textfield">
    <label for="foto" class="col-md-4 control-label">Foto:</label>
    <div class="col-md-6">
     <input type="file" name="fotoImg" class="form-control" required>
     </div>
     @if($errors->has('fotoImg'))
     <span style="color:red;">{{ $errors->first('fotoImg')}}</span>
     @endif
</div>


 <div class="form-group">
    <div class="col-md-6 col-md-offset-4">
        <div class="btn-group">
          <button type="submit" class="btn  btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span>  Crear</button>
          <a href="{{ url('libros/')}}" class="btn btn-success"><span class="glyphicon glyphicon-menu-left"></span> Volver</a>
        </div>
    </div>
 </div>


</form>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/libros/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-title">
      <h2 class="pmd-card-title-text">Editar Libro</h2>
  </div>
<div class="panel-body">


    <form role="form" method="POST" action="{{ route('libros.update', $res->id) }}" enctype="multipart/form-data" class="form-horizontal">
     <input name="_method" type="hidden" value="PUT">
    {{ csrf_field() }}

     <div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label for="descripcion">Descripcion:</label>
      <input type="text" class="form-control" name="descripcion" value="{{$res->descripcion}}">
      @if($errors->has('descripcion'))
      <span style="color:red;">{{ $errors->first('descripcion')}}</span>
      @endif
    </div>

    <div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label  for="cantidad">Cantidad:</label>
      <input type="text" class="form-control" name="cantidad"   value="{{$res->cantidad}}">
      @if($errors->has('cantidad'))
      <span style="color:red;">{{ $errors->first('cantidad')}}</span>
      @endif
</div>

<div class="form-group pmd-textfield pmd-textfield-floating-label">
    <label  for="existencia">Existencia:</label>
      <input type="text" class="form-control" name="existencia"  value="{{$res->existencia}}">
      @if($errors->has('cantidad'))
      <span style="color:red;">{{ $errors->first('cantidad')}}</span>
      @endif
</div>
<div class="form-group pmd-textfield">
    <label for="foto" class="col-md-4 control-label">Foto:</label>
    <div class="col-md-6">
     <input type="file" name="fotoImg" class="form-control" title="Selecciona una Foto" required >
     </div>

</div>

<div class="form-group">
    <div class="col-md-6 col-md-offset-4">
        <div class="btn-group">
          <button type="submit" class="btn  btn-primary">Modificar</button>
          <a href="{{ url('libros')}}" class="btn btn-success">Volver</a>
        </div>
    </div>
 </div>

</form>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/libros/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-title">
      <h2 class="pmd-card-title-text">Libros</h2>
  </div>

	<div class="panel-body">
		<div class="form-group">
		<a href="{{ url('libros/create') }}" class="btn btn-primary ">Nuevo</a>
	</div>
	<div class="pmd-table-card pmd-card pmd-z-depth">
	
	<table id="datatable" class="table pmd-table table-striped table-hover table">

	    <thead>

	        <tr>
	            <th> Descripcion </th>
	            <th> Cantidad </th>
	            <th> Existencia </th>
	            <th>  </th>
	        </tr>
	    </thead>
	    <tbody>
	    	@foreach ($res as $f)

	        <tr>
	            <td>{{ $f->descripcion }}</td>
	            <td>{{ $f->cantidad }}</td>
	            <td>{{ $f->existencia }}</td>
	            <td>
	            	<a href="{{ url('libros/'.$f->id)}}" class="btn btn-success btn-sm" ><span class="glyphicon glyphicon-eye-open"></span></a>
	            	<a href="{{ url('libros/'.$f->id.'/edit')}}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span></a>

	            	<!--form action="{{ route('libros.destroy', $f->id) }}" method="post" onclick="return confirm()"  style="display: inline">
	            		<input type="hidden" name="_method" value="DELETE">
	            		{{ csrf_field() }}
	            		<button type="submit" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span></button>
	            	</form-->
				
				<!--Boton de confirmacion MODAL para Eliminar -->
				<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteComment{{$f->id}}">
                  <span class="glyphicon glyphicon-trash"></span>
                </button>
                <!-- Ventana modal para eliminar -->
                <div class="modal fade" id="deleteComment{{$f->id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog modal-sm" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                        <h3 class="pmd-card-title-text">Desea Eliminar este Registro</h3>
                      </div>
                      <div class="modal-body">
                       Libro : {{$f->descripcion}} 
                       					
                      </div>
                      <div class="modal-footer">
                       		<form action="{{ route('libros.destroy', $f->id) }}" method="post" >
								   <input type="hidden" name="_method" value="DELETE">
								   {{ csrf_field() }}
								   <button type="submit" class="btn btn-warning ">Eliminar</button>
								   <button type="button" class="btn btn-info" data-dismiss="modal">Cerrar</button>
				         	</form>						
                       
                      </div>
                    </div>
                  </div>
                </div>
                <!--Boton de confirmacion MODAL para Eliminar -->	


	            	
	            </td>
	           
	           

	        </tr>
	        @endforeach

	     </tbody>
	    </table>




					




	    	</div>

			</div>


	</div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
 $('.confirmdelete').click(function(e) {
            e.preventDefault();
            var href = $(this).attr('href');
            var jobname = $(this).data('jobname');
            return vex.dialog.confirm({
                message: 'Are you sure you want to withdraw job ' + jobname + '?',
                callback: function(confirmed) {
                    if (confirmed) {
                        window.location.href = href;
                    }
                }
            });
        });
</script>


@endsection

resources/views/libros/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
<div class="pmd-card pmd-card-default pmd-z-depth pmd-card-custom-form">
  <div class="pmd-card-title">
      <h2 class="pmd-card-title-text">Libros</h2>
			 <a href="{{ url('libros/')}}" class="btn btn-success"><span class="glyphicon glyphicon-menu-left"></span> Volver</a>
  </div>


<div class="panel-body">
<div class="row">
	<div class="col-xs-12 col-md-4">

	<img src="{{ '/fotosLibro/'.$res->foto}}" class="img img-thumbnail">

	</div>
	<div class="col-xs-12 col-md-6">
        <table class="table table-">
            <tbody>
                <tr>
                	<th> Titulo </th><td> {{ $res->descripcion}} </td>
                </tr>
                <tr>
                	<th> Autor </th><td> {{ $res->cantidad}}</td></tr>
                <tr>
                	<th> Descripcion </th><td>  {{ $res->existencia}}</td>
            	</tr>
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
@endsection